// temporary file to hold sports data
// Will use cloud firestore in the future and query data from there
export class Sports {
    // Static data holds each sport as an array: [sport name, term, league_code]
    static data = [
        ["Flag Football Sr Boys DI", "Fall", "6TU0L9CN4"],
        ["Flag Football U14 Boys", "Fall", "69J1F14P0"],
        ["Football Sr Boys", "Fall", "2860Y8MWX"],
        ["Soccer Sr Boys DI", "Fall", "2860Y8N5D"],
        ["Soccer Sr Boys DIB", "Fall", "6TU16OCAM"],
        ["Soccer Sr Boys DII", "Fall", "2860Y8SQZ"],
        ["Soccer Sr Boys DIII", "Fall", "2860Y8NIZ"],
        ["Soccer Jr Boys DI", "Fall", "2860Y8N9V"],
        ["Soccer Jr Boys DIB", "Fall", "5GK0HUT9S"],
        ["Soccer Jr Boys DII", "Fall", "2860Y8UL1"],
        ["Soccer Jr Boys DIII", "Fall", "2860Y8QSJ"],
        ["Soccer U14 Boys DI", "Fall", "2860Y8N7H"],
        ["Soccer U14 Boys DII", "Fall", "2860Y8Q3F"],
        ["Soccer U14 Boys DIIB", "Fall", "6W61BEE6T"],
        ["Soccer U13 Boys DI", "Fall", "2860Y8N6T"],
        ["Soccer U13 Boys DII", "Fall", "2860Y8N57"],
        ["Soccer U12 Boys", "Fall", "2AC0DY8K3"],
        ["Soccer U11 Boys", "Fall", "2A70G6P3Q"],
        ["Soccer U10 Boys", "Fall", "2A70G8ET3"],
        ["Volleyball Sr Boys DI", "Fall", "2860Y8NAP"],
        ["Volleyball Sr Boys DII", "Fall", "2860Y8OX1"],
        ["Volleyball Sr Boys DIII", "Fall", "31312JJRO"],
        ["Volleyball Jr Boys DI", "Fall", "2860Y8OON"],
        ["Volleyball Jr Boys DII", "Fall", "2WO1A9SHY"],
        ["Volleyball U14 Boys DI", "Fall", "2860Y8N8R"],
        ["Volleyball U14 Boys DII", "Fall", "2B519NKRQ"],
        ["Volleyball U14 Boys DIII", "Fall", "69X0TA88U"],
        ["Volleyball U12 Boys", "Fall", "3HS0FGO1E"],
        ["Basketball Sr Girls DI", "Fall", "2860Y8ND5"],
        ["Basketball Sr Girls DIB", "Fall", "5550ML66K"],
        ["Basketball Sr Girls DII", "Fall", "2860Y8SQ1"],
        ["Basketball Sr Girls DIII", "Fall", "2860Y8NC7"],
        ["Basketball Jr Girls DI", "Fall", "2860Y8NFT"],
        ["Basketball Jr Girls DII", "Fall", "2860Y8RL9"],
        ["Basketball Jr Girls DIIB", "Fall", "6W51D3JTI"],
        ["Basketball U14 Girls DI", "Fall", "2860Y8NEH"],
        ["Basketball U14 Girls DIB", "Fall", "6W51BX5L7"],
        ["Basketball U14 Girls DII", "Fall", "2B51AIN8X"],
        ["Basketball U14 Girls DIII", "Fall", "2860Y8NGV"],
        ["Basketball U13 Girls DI", "Fall", "2860Y8NHP"],
        ["Basketball U13 Girls DII", "Fall", "6JJ1946S7"],
        ["Basketball U12 Girls", "Fall", "2860Y8SZ9"],
        ["Basketball U11 Girls", "Fall", "2WO1A3OKF"],
        ["Basketball U10 Girls", "Fall", "4D90EZHCI"],
        ["Field Hockey Sr Girls DI", "Fall", "2860Y8N2D"],
        ["Field Hockey Sr Girls DIB", "Fall", "56C0NDMME"],
        ["Field Hockey Sr Girls DII", "Fall", "2860Y8ULR"],
        ["Field Hockey Sr Girls DIII", "Fall", "2860Y8N0X"],
        ["Field Hockey Jr Girls", "Fall", "2860Y8QH1"],
        ["Field Hockey U14 Girls", "Fall", "2860Y8N3J"],
        ["Flag Football Sr Girls DI", "Fall", "67G0YK5EQ"],
        ["Flag Football Sr Girls DII", "Fall", "6W70MH4MT"],
        ["Flag Football Jr Girls DI", "Fall", "6W70N72DI"],
        ["Flag Football U14 Girls", "Fall", "67G0YQS36"],
        ["Soccer Sr Girls Fall DI", "Fall", "2860Y8MYT"],
        ["Soccer Sr Girls Fall DII", "Fall", "2860Y8UMH"],
        ["Soccer Jr Girls Fall", "Fall", "6JH1BRXA6"],
        ["Soccer U14 Girls Fall DI", "Fall", "54Q1C6WLI"],
        ["Soccer U14 Girls Fall DIB", "Fall", "6LZ0E9324"],
        ["Soccer U12 Girls Fall", "Fall", "2860Y8T03"],
        ["Soccer U10 Girls Fall", "Fall", "4SV0P6FX5"],
        ["Swimming Fall", "Fall", "2AD0JA1GX"],
        ["Cross Country HS", "Fall", "2AD0GX5Z3"],
        ["Cross Country Elementary", "Fall", "2AD0H3ETP"],
        ["Basketball Sr Boys DI", "Winter", "2860Y8OYB"],
        ["Basketball Sr Boys DIB", "Winter", "3Z91AJ4A3"],
        ["Basketball Sr Boys DII", "Winter", "2860Y8REJ"],
        ["Basketball Sr Boys DIII", "Winter", "2860Y8MU3"],
        ["Basketball Jr Boys DI", "Winter", "2860Y8NKF"],
        ["Basketball Jr Boys DIB", "Winter", "5GK0JNPYQ"],
        ["Basketball Jr Boys DII", "Winter", "2860Y8UIL"],
        ["Basketball Jr Boys DIII", "Winter", "2860Y8NLH"],
        ["Basketball U14 Boys DI", "Winter", "2860Y8NPD"],
        ["Basketball U14 Boys DIB", "Winter", "5FI12S6NY"],
        ["Basketball U14 Boys DII", "Winter", "2860Y8UK7"],
        ["Basketball U14 Boys DIII", "Winter", "2860Y8NRF"],
        ["Basketball U13 Boys DI", "Winter", "2860Y8NMB"],
        ["Basketball U13 Boys DIB", "Winter", "6W60H5EED"],
        ["Basketball U13 Boys DII", "Winter", "2860Y8NML"],
        ["Basketball U12 Boys", "Winter", "28O0IJYEP"],
        ["Basketball U11 Boys", "Winter", "2A70G9TQF"],
        ["Basketball U10 Boys", "Winter", "2A70GEIW9"],
        ["Hockey Sr Boys DI", "Winter", "2860Y8NS5"],
        ["Hockey Sr Boys NC DI", "Winter", "37M0IXAEZ"],
        ["Hockey Sr Boys NC DIB", "Winter", "4WQ1A8HQI"],
        ["Hockey Sr Boys NC DII", "Winter", "2860Y8STB"],
        ["Hockey Jr Boys DI", "Winter", "67A134XG6"],
        ["Hockey U14 Boys DI", "Winter", "2860Y8NNP"],
        ["Hockey U14 Boys DII", "Winter", "2860Y8Q45"],
        ["Hockey U12 Boys", "Winter", "2A70INJS2"],
        ["Squash Sr Boys", "Winter", "2860Y8P31"],
        ["Squash Jr Boys", "Winter", "2860Y8P3R"],
        ["Squash U14 Boys", "Winter", "2860Y8PSV"],
        ["Badminton Sr Girls", "Winter", "2860Y8P4P"],
        ["Badminton Jr Girls", "Winter", "2860Y8P5F"],
        ["Badminton U14 Girls", "Winter", "2860Y8P61"],
        ["Badminton U13 Girls", "Winter", "2860Y8MWF"],
        ["Hockey Sr Girls DI", "Winter", "2860Y8NMV"],
        ["Hockey Sr Girls DIB", "Winter", "2860Y8NQX"],
        ["Hockey Sr Girls DII", "Winter", "2860Y8UJH"],
        ["Squash Sr Girls", "Winter", "5460GTE91"],
        ["Volleyball Sr Girls DI", "Winter", "2860Y8NVH"],
        ["Volleyball Sr Girls DIB", "Winter", "4S70A7NK3"],
        ["Volleyball Sr Girls DII", "Winter", "2BO1AXBXR"],
        ["Volleyball Sr Girls DIII", "Winter", "2860Y8NSR"],
        ["Volleyball Jr Girls DI", "Winter", "2860Y8NWF"],
        ["Volleyball Jr Girls DII", "Winter", "2BO1A0M4A"],
        ["Volleyball Jr Girls DIII", "Winter", "2860Y8PC5"],
        ["Volleyball U14 Girls DI", "Winter", "2860Y8P97"],
        ["Volleyball U14 Girls DII", "Winter", "2BO1C5CTB"],
        ["Volleyball U14 Girls DIIB", "Winter", "6W70QOZIF"],
        ["Volleyball U14 Girls DIII", "Winter", "2860Y8NT9"],
        ["Volleyball U13 Girls DI", "Winter", "2860Y8NXX"],
        ["Volleyball U13 Girls DII", "Winter", "47I0DJ4P6"],
        ["Volleyball U12 Girls", "Winter", "2860Y8T1X"],
        ["Volleyball U11 Girls", "Winter", "2WO1A1OUT"],
        ["Volleyball U10 Girls", "Winter", "4D90F23EC"],
        ["Alpine Skiing", "Winter", "2AD0JZI99"],
        ["Alpine Skiing U14", "Winter", "4JH0VI7TF"],
        ["Curling Div I", "Winter", "2AD0KCRKF"],
        ["Curling Div II", "Winter", "2IN0LB0PI"],
        ["Curling U14 Coed", "Winter", "4RW0RVLZG"],
        ["Futsal U14 Coed", "Winter", "6TU0LO9ZS"],
        ["Nordic Ski", "Winter", "2AD0KB2H7"],
        ["Snowboarding", "Winter", "2AF0JA088"],
        ["Swimming HS Coed", "Winter", "2AD0JI15P"],
        ["Swimming ELE Coed", "Winter", "2AD0JV1G7"],
        ["Baseball Sr Boys DI", "Spring", "2860Y8Q1V"],
        ["Baseball Sr Boys DIB", "Spring", "5FI11KHT3"],
        ["Golf Sr Boys", "Spring", "6JG19ROTT"],
        ["Golf Jr Boys", "Spring", "6JG18GGK7"],
        ["Lacrosse Sr Boys", "Spring", "2860Y8OBX"],
        ["Lacrosse U14 Boys", "Spring", "2860Y8Q4R"],
        ["Rugby Sr Boys 15's", "Spring", "2860Y8OA1"],
        ["Rugby Sr Boys 7's", "Spring", "41F1BW798"],
        ["Rugby Jr Boys 15's", "Spring", "2860Y8O2N"],
        ["Rugby Jr Boys 7's", "Spring", "3RB0NWL58"],
        ["Rugby U14 Boys DI Touch", "Spring", "2860Y8O07"],
        ["Rugby U14 Boys DII Touch", "Spring", "3PJ0FSNX6"],
        ["Slow Pitch Sr Boys", "Spring", "2860Y8OD1"],
        ["Slow Pitch U14 Boys DI", "Spring", "2860Y8SCT"],
        ["Slow Pitch U14 Boys DII", "Spring", "2860Y8O7J"],
        ["Slow Pitch U12 Boys", "Spring", "2A70GHFBT"],
        ["Slow Pitch U11 Boys", "Spring", "2L8199CL7"],
        ["Tennis Sr Boys", "Spring", "2860Y8PUL"],
        ["Tennis Jr Boys", "Spring", "2860Y8ODJ"],
        ["Tennis U14 Boys", "Spring", "2860Y8PTJ"],
        ["Golf Sr Girls", "Spring", "6JG18JH77"],
        ["Rugby Sr Girls 7's DI", "Spring", "37N0DVVAB"],
        ["Rugby Sr Girls 7's DIB", "Spring", "5CP0RKUV9"],
        ["Rugby Sr Girls 7's DII", "Spring", "6LK19FC1T"],
        ["Rugby Jr Girls 7's", "Spring", "5CP0RQYAV"],
        ["Rugby U14 Girls Touch", "Spring", "422148P60"],
        ["Soccer Sr Girls Spring DI", "Spring", "2860Y8O0H"],
        ["Soccer Sr Girls Spring DII", "Spring", "2860Y8Q2L"],
        ["Soccer Jr Girls Spring", "Spring", "2860Y8O3V"],
        ["Soccer U14 Girls Spring DI", "Spring", "2860Y8O57"],
        ["Soccer U12 Girls Spring", "Spring", "3FN0YCA5F"],
        ["Softball Sr Girls DI", "Spring", "2860Y8O83"],
        ["Softball Sr Girls DII", "Spring", "2860Y8OJF"],
        ["Softball Jr Girls", "Spring", "2860Y8O9B"],
        ["Softball U14 Girls", "Spring", "2860Y8OAP"],
        ["Softball U13 Girls", "Spring", "2860Y8OCF"],
        ["Softball U12 Girls", "Spring", "2860YFJVS"],
        ["Tennis Sr Girls", "Spring", "2860Y8PJD"],
        ["Tennis Jr Girls", "Spring", "2860Y8PKR"],
        ["Tennis U14 Girls Doubles", "Spring", "2860Y8PLT"],
        ["Tennis U13 Girls", "Spring", "2860Y8PMN"],
        ["Badminton Sr Coed", "Spring", "2860Y8PYD"],
        ["Badminton Jr Coed", "Spring", "2860Y8PZR"],
        ["Badminton U14 Coed", "Spring", "2860Y8Q0X"],
        ["Track & Field HS Coed", "Spring", "2AD0KGHQA"],
        ["Track & Field ELE Coed", "Spring", "2AD0KIP95"],
        ["Ultimate Frisbee SR DI", "Spring", "2DR0EO85A"],
        ["Ultimate Frisbee SR DII", "Spring", "2WO19VYCD"],
        ["Ultimate Frisbee SR DIII", "Spring", "6JH1DBQR7"],
        ["Ultimate Frisbee Jr DI", "Spring", "4JI0LHHYU"],
        ["Ultimate Frisbee Jr DII", "Spring", "6VG13HJP3"],
        ["Ultimate Frisbee U14 Coed DI", "Spring", "6JH1C3LFN"],
        ["Ultimate Frisbee U14 Coed DII", "Spring", "6JH1C8K13"],
        ["Ultimate Frisbee U12 Coed", "Spring", "69K0HJNPP"]
    ];

    /**
     * Returns the sport record matching the given league code.
     * @param {string} leagueCode - The league code to search for.
     * @returns {Array|undefined} The sport record [name, term, leagueCode] or undefined if not found.
     */
    static getSportByLeagueCode(leagueCode) {
        return this.data.find(sport => sport[2] === leagueCode);
    }

    /**
     * Returns the sport record matching the given sport name.
     * @param {string} name - The sport name to search for.
     * @returns {Array|undefined} The sport record [name, term, leagueCode] or undefined if not found.
     */
    static getSportByName(name) {
        return this.data.find(sport => sport[0] === name);
    }

    /**
     * Returns all sports that match the given term (e.g., "Fall", "Winter", "Spring").
     * @param {string} term - The term/season to filter by.
     * @returns {Array} An array of sports records.
     */
    static getSportsByTerm(term) {
        return this.data.filter(sport => sport[1] === term);
    }

    /**
     * Returns all sport records.
     * @returns {Array} An array of all sports records.
     */
    static getAllSports() {
        return this.data;
    }
}
